<a href="https://colab.research.google.com/github/Jaswanth-03/arya_assignment/blob/main/Data_scientist_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importing dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Data Exploration

In [ ]:
import pandas as pd
data=pd.read_csv("/content/drive/MyDrive/Arya_DataScientist_Assignment/training_set.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 59 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  3910 non-null   int64  
 1   X1          3910 non-null   float64
 2   X2          3910 non-null   float64
 3   X3          3910 non-null   float64
 4   X4          3910 non-null   float64
 5   X5          3910 non-null   float64
 6   X6          3910 non-null   float64
 7   X7          3910 non-null   float64
 8   X8          3910 non-null   float64
 9   X9          3910 non-null   float64
 10  X10         3910 non-null   float64
 11  X11         3910 non-null   float64
 12  X12         3910 non-null   float64
 13  X13         3910 non-null   float64
 14  X14         3910 non-null   float64
 15  X15         3910 non-null   float64
 16  X16         3910 non-null   float64
 17  X17         3910 non-null   float64
 18  X18         3910 non-null   float64
 19  X19         3910 non-null  

In [ ]:
data

X1    X2    X3     X4    X5    X6    X7    X8    X9   X10  ...  X49  \
0     0.00  0.00  4.34   0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
1     0.00  0.56  0.56   0.00  1.12  0.56  2.25  0.00  0.00  0.56  ...  0.0   
2     0.00  0.00  0.00   0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
3     0.64  0.00  0.64   0.00  1.93  0.00  0.00  0.00  0.00  0.00  ...  0.0   
4     0.58  0.00  0.00  35.46  0.58  0.00  0.58  0.58  0.00  0.00  ...  0.0   
...    ...   ...   ...    ...   ...   ...   ...   ...   ...   ...  ...  ...   
3905  0.00  0.00  0.00   0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
3906  0.00  0.00  0.00   0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
3907  0.12  0.00  0.12   0.00  0.00  0.25  0.00  0.00  0.00  0.00  ...  0.0   
3908  0.00  0.00  0.00   0.00  0.00  0.00  0.00  3.12  0.00  0.00  ...  0.0   
3909  0.96  0.00  0.48   0.00  0.00  0.96  0.00  0.00  0.48  0.00  ...  0.0   

        X50  X51    X52    X53    X54     X55  X56  X57  Y  
0     0.000  0.0  1.342  0.000  0.000   1.200    2   12  0  
1     0.083  0.0  0.503  0.000  0.083  16.304  148  375  1  
2     0.000  0.0  0.000  0.000  0.000   1.000    1    5  0  
3     0.000  0.0  0.462  0.370  0.000   2.440   22  122  1  
4     0.000  0.0  0.239  0.239  0.000   3.338  123  207  1  
...     ...  ...    ...    ...    ...     ...  ...  ... ..  
3905  0.000  0.0  0.000  0.000  0.000   1.714    4   12  0  
3906  0.000  0.0  0.000  0.000  0.000   2.000    3    4  0  
3907  0.093  0.0  0.023  0.000  0.000   1.247    5  131  0  
3908  0.198  0.0  0.198  0.198  0.000   3.857   25   81  1  
3909  0.818  0.0  0.175  0.467  0.116   9.560  259  717  1  

[3910 rows x 58 columns]

# removing unwanted columns

In [ ]:
data=data.drop(columns=["Unnamed: 0"])

In [ ]:
data.Y.unique()

array([0, 1])

# finding null values

In [ ]:
data.isna().sum().to_numpy()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# finding noisy data

In [ ]:
data.apply(lambda x: x!=x).sum()

X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
X24    0
X25    0
X26    0
X27    0
X28    0
X29    0
X30    0
X31    0
X32    0
X33    0
X34    0
X35    0
X36    0
X37    0
X38    0
X39    0
X40    0
X41    0
X42    0
X43    0
X44    0
X45    0
X46    0
X47    0
X48    0
X49    0
X50    0
X51    0
X52    0
X53    0
X54    0
X55    0
X56    0
X57    0
Y      0
dtype: int64

In [ ]:
data["Y"].value_counts()

0    2376
1    1534
Name: Y, dtype: int64

# Splitting Dataset as X and Y

In [ ]:
X_data=data.drop(columns="Y")
Y_data=data["Y"]

In [ ]:
X_data.shape,Y_data.shape

((3910, 57), (3910,))

# Train Test Splitting

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data,Y_data,test_size=0.3,stratify=Y_data,random_state=100)

In [ ]:
y_train.value_counts()

0    1663
1    1074
Name: Y, dtype: int64

# Model Building

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier = Sequential()

In [ ]:
classifier.add(Dense(units = 29, input_dim = 57))
classifier.add(Dense(units = 29 ))
classifier.add(Dense(units = 29))
classifier.add(Dense(units = 1,  activation = 'sigmoid'))

In [ ]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
classifier.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 29)                1682      
                                                                 
 dense_9 (Dense)             (None, 29)                870       
                                                                 
 dense_10 (Dense)            (None, 29)                870       
                                                                 
 dense_11 (Dense)            (None, 1)                 30        
                                                                 
Total params: 3,452
Trainable params: 3,452
Non-trainable params: 0
_________________________________________________________________


# model training

In [ ]:
classifier.fit(X_train,y_train, verbose=1,validation_split=0.2,epochs=500)

Epoch 1/500
69/69 [==============================] - 0s 6ms/step - loss: 0.2005 - accuracy: 0.9255 - val_loss: 0.3669 - val_accuracy: 0.9179
Epoch 2/500
69/69 [==============================] - 0s 6ms/step - loss: 0.1943 - accuracy: 0.9255 - val_loss: 0.4168 - val_accuracy: 0.9161
Epoch 3/500
69/69 [==============================] - 0s 5ms/step - loss: 0.2144 - accuracy: 0.9219 - val_loss: 0.3742 - val_accuracy: 0.9215
Epoch 4/500
69/69 [==============================] - 0s 5ms/step - loss: 0.1959 - accuracy: 0.9242 - val_loss: 0.4236 - val_accuracy: 0.9161
Epoch 5/500
69/69 [==============================] - 0s 5ms/step - loss: 0.2032 - accuracy: 0.9255 - val_loss: 0.4133 - val_accuracy: 0.9142
Epoch 6/500
69/69 [==============================] - 0s 6ms/step - loss: 0.1942 - accuracy: 0.9260 - val_loss: 0.3934 - val_accuracy: 0.9161
Epoch 7/500
69/69 [==============================] - 0s 5ms/step - loss: 0.1977 - accuracy: 0.9255 - val_loss: 0.4471 - val_accuracy: 0.8631
Epoch 8/500
6

# model evaluation

In [ ]:
classifier.evaluate(
  x=X_test,
  y=y_test,
  batch_size=None,
  verbose=1,use_multiprocessing=True
)

37/37 [==============================] - 0s 1ms/step - loss: 0.2539 - accuracy: 0.9224


[0.25394997000694275, 0.9224211573600769]

In [ ]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# metrics

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[675  38]
 [ 53 407]]
0.9224211423699915
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       713
           1       0.91      0.88      0.90       460

    accuracy                           0.92      1173
   macro avg       0.92      0.92      0.92      1173
weighted avg       0.92      0.92      0.92      1173

